<a href="https://colab.research.google.com/github/Innovatewithapple/LogRegPrac/blob/main/LogisticPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [3]:
df = pd.read_csv('/content/customer_churn_dataset-testing-master.csv')

In [4]:
df.sample(5)

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
38643,38644,37,Female,12,9,0,11,Premium,Monthly,729,3,0
55728,55729,36,Male,41,13,7,18,Basic,Quarterly,653,18,1
58956,58957,31,Male,28,7,5,30,Standard,Monthly,692,18,1
46192,46193,63,Female,32,24,7,20,Premium,Quarterly,536,22,1
39240,39241,20,Female,29,22,5,25,Standard,Monthly,258,20,1

In [5]:
x = df.drop(columns='Churn')
y = df['Churn']

In [6]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [8]:
# encoding
onehot = OneHotEncoder(handle_unknown='ignore', drop='first', sparse_output=False)

In [10]:
x_train_encode = onehot.fit_transform(x_train[['Gender','Subscription Type','Contract Length']])
x_test_encode = onehot.transform(x_test[['Gender','Subscription Type','Contract Length']])

In [13]:
cols = ['CustomerID','Age','Tenure','Usage Frequency','Support Calls','Payment Delay','Total Spend','Last Interaction']
x_train_num = x_train[cols].reset_index(drop=True)
x_test_num = x_test[cols].reset_index(drop=True)

x_train_encode = pd.DataFrame(x_train_encode,columns=onehot.get_feature_names_out())
x_test_encode = pd.DataFrame(x_test_encode,columns=onehot.get_feature_names_out())

x_train_final = pd.concat([x_train_num,x_train_encode],axis=1)
x_test_final = pd.concat([x_test_num,x_test_encode],axis=1)

In [14]:
x_train_final

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Gender_Male,Subscription Type_Premium,Subscription Type_Standard,Contract Length_Monthly,Contract Length_Quarterly
0,5872,54,7,29,0,27,568,16,0.0,1.0,0.0,0.0,0.0
1,40571,61,49,10,10,0,151,21,0.0,1.0,0.0,0.0,0.0
2,201,36,24,29,1,26,566,8,1.0,1.0,0.0,1.0,0.0
3,64038,59,27,12,9,24,257,9,0.0,0.0,0.0,1.0,0.0
4,13250,30,18,8,0,24,997,17,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45056,62571,50,38,11,5,28,568,5,1.0,1.0,0.0,0.0,1.0
45057,38159,53,44,30,3,3,447,21,1.0,1.0,0.0,1.0,0.0
45058,861,33,47,9,2,26,454,6,0.0,0.0,1.0,0.0,1.0
45059,15796,24,57,19,10,9,948,27,1.0,1.0,0.0,0.0,0.0
45060,56423,33,34,19,6,17,554,2,0.0,0.0,1.0,0.0,1.0

In [15]:
# scaling
scale = StandardScaler()
x_train_scale = scale.fit_transform(x_train_final)
x_test_scale = scale.transform(x_test_final)

In [16]:
model = LogisticRegression()
model.fit(x_train_scale,y_train)

LogisticRegression()

In [17]:
print('coeff:',model.coef_[0])
print('intercept:',model.intercept_)

coeff: [ 1.28843414  0.25001597  0.60487407 -0.53079231  1.02107861  1.82875512
 -0.27226094 -0.00623128 -0.56185406 -0.0534573  -0.04684243  0.16744203
 -0.06318793]
intercept: [-0.2946395]

In [18]:
y_pred = model.predict(x_test_scale)

In [21]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.8635116242945167
[[8875 1259]
 [1377 7802]]
              precision    recall  f1-score   support

           0       0.87      0.88      0.87     10134
           1       0.86      0.85      0.86      9179

    accuracy                           0.86     19313
   macro avg       0.86      0.86      0.86     19313
weighted avg       0.86      0.86      0.86     19313